export enum CallStatus {
	INITIALIZATION = 'INITIALIZATION',
	STAND_BY = 'STAND_BY',
	STARTING_CALL = 'STARTING_CALL',
	NO_ANSWER = 'NO_ANSWER',
	CALL_ACCEPTED = 'CALL_ACCEPTED',
	CALL_REJECTED = 'CALL_REJECTED',
	RECEIVING_CALL = 'RECEIVING_CALL',
	IN_PROGRESS = 'IN_PROGRESS',
}
